name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1
  geolocator: ^10.1.0
  weather: ^3.1.1
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/ui/launcher.png" 
  android: true 
  ios: true 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/weather/
    - assets/images/ui/

  fonts:
  - family: BeVietnam
    fonts:
      - asset: assets/fonts/BeVietnam.otf
  - family: BeVietnamThin
    fonts:
      - asset: assets/fonts/BeVietnamThin.otf
  - family: Switzer
    fonts:
      - asset: assets/fonts/Switzer.otf
